### ISSUE TITLE
User Auth Review

### ISSUE THREAD

**Issue by ssoonmi** [richierob62/trolle#6]
### Login / Signup Forms
- [x] width of inputs and submit button should be the same
- [x] should be more white space before the top of the form
- [x] text needs to be slightly bigger
- [x] submit button should be taller
- [x] should have a button to log in as a demo user on both forms
- [x] when I try to do an unsuccessful log in and try to switch to the sign up form, the errors don't get cleared

### NavBar
- [x] navbar when logged in looks different than when you are not logged in

### Sign Out
- [x] when a user is signed in, you should render the profile dropdown menu with the logout button as a menu item

**Comment by richierob62** [comment]
Re: width of inputs and submit button should be the same

I'm seeing them the same width.  Please share your screen and show me what you see tomm.  Thanks.

**Comment by richierob62** [comment]
done

**Comment by ssoonmi** [comment]
- [ ] when the profile dropdown menu is open, clicking anywhere outside of it should close the menu
- [ ] logout button text is not vertically centered
- [ ] should have a little bit of spacing between the logout button and the end of the dropdown menu

**Comment by richierob62** [comment]
done

**Comment by ssoonmi** [comment]
- [ ] logout button text is still not vertically centered when you hover over the item

**Comment by richierob62** [comment]
done
